### ISSUE TITLE
Running "File" > "New" shows an error

### ISSUE THREAD

**Issue by rsyh93** [la9527/mdir.js#2]
**Describe the bug**
Running "New" from the "File" menu shows an error, and seems to be unimplemented in code.

**To Reproduce**
1. Press F12 to access the pulldown menu
2. Go to "File". Your cursor should be on "New"
3. Press Enter.

**Expected behavior**
Similar to the "Mkdir" function, a dialog box should pop up, asking for a name for the new file.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.10

**Comment by la9527** [comment]
Thank you for reporting. It has been reflected in version 1.2.6.
