### ISSUE TITLE
Smarter Mount menu entries for Linux

### ISSUE THREAD

**Issue by rsyh93** [la9527/mdir.js#3]
**Is your feature request related to a problem? Please describe.**
Currently, the mount menu shows **every** mount point, which can get a bit unwieldy...

![mount pane showing 56 mount points](https://user-images.githubusercontent.com/2167469/116775972-11e25900-aa34-11eb-9733-0392774a2d60.png)

**Describe the solution you'd like**
List only the mount points relevant to a non-administrative user: that is, (encrypted/unencrypted) partitions and removable media.

**Additional context**
See [`jamielinux/bashmount`](https://github.com/jamielinux/bashmount) for a small bash utility that fetches necessary info in Linux.

**Comment by la9527** [comment]
Thank you for providing multiple patches.
